version: '3.7'

networks:
  birdboard-prod:

services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - php
    links:
      - php
    networks:
      - birdboard-prod
  php:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: php
    networks:
      - birdboard-prod
    env_file:
      - ./.env