version: '3.7'

networks:
  birdboard-prod:

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=birdboard
      - MYSQL_DATABASE=birdboard
      - MYSQL_USER=birdboard
      - MYSQL_PASSWORD=secret
    networks:
      - birdboard-prod
  nginx:
    restart: always
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - php
      - mysql
    links:
      - php
    networks:
      - birdboard-prod
  php:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: php
    networks:
      - birdboard-prod
    links:
      - mysql
    env_file:
      - ./.env