apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - multi-k8s.ml
        - www.multi-k8s.ml
      secretName: multi-k8s-ml
  rules:
  - host: multi-k8s.ml
    http:
      paths:
        - path: /
          backend:
            serviceName: birdboard-service
            servicePort: 80
  # - http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: birdboard-service
  #         servicePort: 80
